version: "3"

services:
  builder:
    image: tachang/openfang-buildenv
    environment:
      EXAMPLE: development
    volumes:
      - ".:/src"
      - "./legacy_src:/openfang/legacy_src"
      - "./patches:/openfang/patches"
      - "./config:/openfang/config"
      - "./buildscripts:/openfang/buildscripts"
      - "./fs:/openfang/fs"
      - "./sharedfiles:/sharedfiles"
    ports:
      - "69:69/udp"
    cap_add:
      - ALL
  nfs:
    image: erichough/nfs-server
    environment:
      NFS_EXPORT_0: "/sharedfiles/rootfs  73.63.166.167/32(rw,no_subtree_check,no_root_squash)"
      NFS_LOG_LEVEL: "DEBUG"
    volumes:
      - "./sharedfiles:/sharedfiles"
    cap_add:
      - SYS_ADMIN
    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "111:111/tcp"
      - "111:111/udp"
      - "32765:32765/tcp"
      - "32765:32765/udp"
      - "32767:32767/tcp"
      - "32767:32767/udp"
    security_opt:
      - apparmor=erichough-nfs

